ChickPro0/morgorithm

config/database.js, routes/index.js, server.js
main 데이터 DB 연동 완료했습니다.
@fiatluxdaisy  확인요망
=> index main data route

react-project/src/components/PatientTable.css, react-project/src/components/SuspiciousTable.css, react-project/src/components/SuspiciousTable.jsx, react-project/src/pages/Main01.css, react-project/src/pages/Main01.jsx
=> table css 수정

routes/index.js
index.js 코드수정했습니다.
데이터연동 오류 수정
/patients -> 오타수정했습니다.
데이터연동 오류 수정
쿼리수정.
reject->throw
resolve -> res.json
=> router modify

react-project/package-lock.json, react-project/package.json, react-project/src/App.js, react-project/src/components/Login.jsx, routes/user.js, server.js
백엔드 로그인 기능 구현 완료하였습니다.
확인 및 머지 부탁드리겠습니다.
=> login connection

react-project/src/App.js, react-project/src/components/Header.jsx, react-project/src/components/Login.jsx, react-project/src/contexts/UserContext.js, react-project/src/pages/Detailpage.jsx, routes/detail.js, routes/user.js, server.js
로그인 / 로그아웃 구현 및 세션 정보 구현 완료했습니다.
세션 정보 헤더 연동 일부 완성했습니다.
=> login session

routes/comment.js, routes/index.js, server.js
* 수정
1. 전체 데이터 
sepsis_score 추가
코멘트 테이블 조인
2. 패혈증 의심 환자
환자 테이블만 -> patient, data, comments 연결 
관리자 페이지 설정 값 불러오는 것으로 변경
-----------------------------------------------
* 생성
comment CRUD 연동했습니다.
=> comment crud

routes/comment.js, routes/index.js
index.js 패혈증 의심 쿼리문 수정
comment.js 코멘트 조회 쿼리문 수정
=> modify index comment

routes/comment.js
=> real modify comment

react-project/src/App.js, react-project/src/components/AdminAddModal.jsx, react-project/src/components/AdminScoreModal.jsx, react-project/src/components/SepsisScoreContext.jsx, react-project/src/pages/Adminpage.css, react-project/src/pages/Adminpage.jsx
관리자 페이지
- 유저목록 페이지네이션 삭제 후 스크롤링 기능 추가 (부트스트랩 css 충돌 이슈)
- 유저목록 페이지 삭제 기능 구현
- 테이블 row 클릭 시 해당되는 row 빨간색 테두리 보이도록 설정 (선택 여부 보여주기)
- row 클릭 확인 후 삭제버튼 누르면 삭제 되도록 axios로 DB 연동
- 유저목록 페이지 추가 기능 구현
- 추가 버튼 클릭 시 adminaddmodal창 열기
- adminaddmodal창에서 추가할 user 정보 입력 후 axios로 DB 연동
- adminscoremodal(패혈증 점수 설정 모달창)에서 패혈증 점수 입력 후 axios로 DB 연동
- useContext로 전역에서 패혈증 점수 설정 할 수 있도록 기능 구현
=> admin addmodal, scoremodal

routes/detail.js, routes/user.js
detail.js 변경사항
SQL 쿼리문 수정 및 DB 확인
요청 본문에서 patient_id 구조 분해 할당
patient_id 매개변수 포함하여 SQL 쿼리에 데이터 바인딩 추가
Promise 사용하여 쿼리의 비동기 실행 처리
콜백 함수 내 쿼리 실행 중 오류 발생하면 Promise 거부하고 오류 전달
오류 발생하지 않으면 Promise 이행하고 쿼리 결과 전달
쿼리 결과 JSON 응답으로 클라이언트에 반환
=> Add data binding and error handling to patient detail API endpoint

react-project/package-lock.json, react-project/package.json, react-project/src/components/DetailAllTable.css, react-project/src/components/DetailAllTable.jsx, react-project/src/components/SingleTable.css, react-project/src/components/SingleTable.jsx, react-project/src/components/detailPcolumns.js, react-project/src/components/detailallcolumns.js, react-project/src/pages/Detailpage.jsx, react-project/src/pages/Main01.jsx, routes/detail.js, server.js
detailpage css
- table 색상, hover
- scroll
=> detailpage css confirm

react-project/src/components/Graph.css, react-project/src/components/GraphLine.jsx, routes/detail.js
상세페이지
- 그래프 실제 DB와 연동
- 그래프 색상 변경
- 체크박스 ALL, ALLOUT 버튼 추가 및 기능 구현
- 체크박스 데이터 변경으로 인한 UI변경
=> detail graph change

react-project/src/pages/Detailpage.jsx, routes/detail.js
/info 경로에서 환자 정보 가져오는 SQL 쿼리문 수정
patient 테이블과 data 테이블 조인하여 sepsis_score 정보 조회하도록 변경
admission_duration 컬럼 추가하여 입원 기간 계산
/graph 경로에서 환자 그래프를 가져오는 SQL 쿼리문 수정
/alldata 경로에서 모든 환자 데이터 상세하게 가져오는 SQL 쿼리문 추가
=> detail routing

react-project/src/pages/Detailpage.jsx, routes/detail.js
//info & //alldata
record_time을 'YYYY-MM-DD HH:MM' 형식으로 포맷팅
=> Update patient information and all data detail queries

react-project/src/App.js, react-project/src/components/AdminAddModal.css, react-project/src/components/AdminScoreModal.css, react-project/src/components/Graph.css, react-project/src/components/GraphLine.jsx, react-project/src/components/Header.css, react-project/src/components/Header.jsx, react-project/src/components/Login.jsx, react-project/src/pages/Adminpage.css, react-project/src/pages/Adminpage.jsx, react-project/src/pages/Detailpage.jsx
- 로그인
- 로그인 시 각 직업에 맞는 페이지로 이동하도록 로그인페이지 / 헤더페이지 수정
- 그래프
- 상세그래프 및 체크박스 가독성 있게 css 수정
- 전체적인 글꼴 통일함
확인 부탁드립니다 :)
=> login graph 

react-project/src/App.js, react-project/src/components/AdminAddModal.css, react-project/src/components/AdminAddModal.jsx, react-project/src/components/AdminScoreModal.css, react-project/src/components/AdminScoreModal.jsx, react-project/src/components/CommentModal.css, react-project/src/components/CommentModal.jsx, react-project/src/contexts/SepsisScoreContext.jsx, react-project/src/pages/Main01.jsx
- Main페이지 comment 모달창 수정 기능 구현 및 css 수정
- 관리자페이지 패혈증 점수 설정 모달, 사용자 추가 모달 css 수정
확인 부탁드립니다 :)
=> comment modify and css, addmodal scoremodal css

react-project/src/components/AdminScoreModal.css, react-project/src/components/AdminScoreModal.jsx, react-project/src/pages/Adminpage.css, react-project/src/pages/Adminpage.jsx
- 관리자 페이지
- 전체적 버튼 크기 조정
- 패혈증 설정 숫자만 입력하도록 정규 표현식으로 수정
- 입력 관련 안내 문구 띄우기
확인 부탁드려요:)
=> adgmin css

react-project/package-lock.json, react-project/package.json, react-project/src/components/DetailAllTable.jsx, react-project/src/components/Graph.css, react-project/src/components/GraphLine.jsx, react-project/src/components/ModalGraph.css, react-project/src/components/PatientTable.css, react-project/src/components/PatientTable.jsx, react-project/src/components/PdfFile.jsx, react-project/src/components/SuspiciousTable.css, react-project/src/components/SuspiciousTable.jsx, react-project/src/components/columns.js, react-project/src/components/detailPcolumns.js, react-project/src/components/detailallcolumns.js, react-project/src/pages/Detailpage.css, react-project/src/pages/Detailpage.jsx, react-project/src/pages/Main01.css, react-project/src/pages/Main01.jsx
mainpage 수정
- 기존 디자인에서 버튼에 따라 의심/ 전체 테이블이 보이게 수정
- Aron Score 폰트 굵기, 색깔 수정
- SuspiciousTable 페이지네이션 설정
detailPage 수정
- Input 날짜 추가
- 날짜 필터링 테이블 연동
- 날짜 필터링 그래프 연동
- PdfFile 테이블 날짜 필터링 연동
=> mainpage modify, pdffile modify, detailpage modify

react-project/src/components/AdminAddModal.css, react-project/src/components/AdminAddModal.jsx, react-project/src/components/AdminScoreModal.css, react-project/src/components/AdminScoreModal.jsx, react-project/src/pages/Adminpage.css, react-project/src/pages/Adminpage.jsx
관리자 페이지 
- 체크 박스 및 중복 삭제 기능 추가
- 사용자 목록 이름으로 검색 기능 추가
- 패혈증 점수 설정 모달에서 이전 점수 보여주는 기능 추가
- css 디테일 수정
확인 부탁드립니다 :)
=> admin page checkbox search beforescore add

react-project/src/components/Header.jsx, react-project/src/components/PatientTable.jsx, react-project/src/components/SuspiciousTable.jsx, react-project/src/pages/Adminpage.jsx, react-project/src/pages/Detailpage.jsx, react-project/src/pages/Main01.css, react-project/src/pages/Main01.jsx
관리자 페이지
- 사용자 목록 삭제시 알림창 구현
- 헤더 60분 만료되면 00:-01로 보이던 현상 수정
메인 페이지
- 전체/의심환자 테이블 연동 토글버튼으로 수정
- 환자 상태 설정 모달창 css 수정
=> adminpage and main add

react-project/src/components/DetailAllTable.css, react-project/src/components/DetailAllTable.jsx, react-project/src/components/GraphLine.jsx, react-project/src/components/PatientTable.jsx, react-project/src/components/SuspiciousTable.jsx, react-project/src/pages/Detailpage.jsx, react-project/src/pages/Main01.jsx
suspiciousTable에 새로운 환자 데이터가 들어왔을때,
main페이지에서 alert로 새로 들어온 환자 데이터 알림.
=> maipage, suspicioustable alert

react-project/src/components/AdminAddModal.css, react-project/src/components/AdminAddModal.jsx, react-project/src/pages/Adminpage.jsx
관리자페이지
- 사용자 목록 직급 (숫자 -> 직급이름) 표시 변경
사용자 목록 추가 모달
- 추가 데이터 이름 영어-> 한글 변경
- 정규표현식을 이용해 제한을 걸어,
사번, 비밀번호, 이름, 클래스를 잘못 입력한 경우 확인 버튼 눌렀을 때 각 상황에 맞는 알림창 뜨도록 수정함
확인 부탁 드립니다 :)
=> adminpage and addscoremodal modify

package-lock.json, package.json, react-project/src/components/CommentModal.css, react-project/src/components/CommentModal.jsx, routes/comment.js
코멘트 모달 업데이트 - 코멘트 상세 정보 및 정렬 구현
CommentModal.jsx
1. 코멘트 작성시, 코멘트 생성 날짜 시간, 담당직급, 담당자명 기록
(코멘트 조회시, 이미 기록된 코멘트 담당직급, 담당자명 로그인 된 사용자 정보로 바뀌지 않게 처리)
2. 코멘트 수정 시, 수정 시점 날짜, 시간,  담당직급, 담당자명으로 갱신
4. 가장 최근 등록, 수정된 코멘트가 모달창 상단에 자동 정렬되게 처리
5. 코멘트 생성 시간 24시간 형식으로 포맷팅 / 시간 오차(대략 3시간) 해결 
CommentModal.css
코멘트 모달창 height 조정, 코멘트 입력창, 닫힘버튼 위치 수정
코멘트 내용 줄바꿈 추가, 볼드처리
Comment.js
쿼리문 추가, 변경 및 작성일자 정보 받아옴 등 코멘트 모달창 연동
추가 구현하면 좋을 내용
코멘트 내용 삭제 버튼 alert (+동일 user_id로 로그인시에만 삭제처리)
코멘트 내용 수정 창 수정(창 사이즈 키우고 창크기 조절 막기(창크기 조절시 수정이 안되는 오류해결), 
코멘트 모달창에 환자 id 옆에 환자 이름도 띄우기(시도했으나 실패ㅎ)
=> Comment Modal Update - Details and Sorting

react-project/src/components/DetailAllTable.css, react-project/src/components/GraphLine.jsx, react-project/src/components/SuspiciousTable.jsx, react-project/src/pages/Main01.jsx
=> detailAllTable css modify
